trigger: example_repository_dispatch
title: Example repository_dispatch
description: An example of how to use the repository_dispatch step
steps:
- type: repository_dispatch
  eventType: special_merge
  repository: apm-pub-org/d3-1
