trigger: test-remove
title: Test remove
description: Remove the current issue or pull request from the project board for the docs content first responder
surfaces:
  - issue
  - pull_request
  - discussion
steps:
  - type: repository_dispatch
    eventType: test_rd
