name: copy contetns

on:
  push

jobs:
  copy:
    name: copy
    runs-on: ubuntu-latest
    steps:
    - name: check out repo content
      uses: actions/checkout@v2

    - name: Read and assign
      id: output_test
      run: |
        echo "MYVAR=$(cat .github/workflows/review-template.md)" >> $GITHUB_ENV
    - name: use
      run: |
        echo $MYVAR

    # test to see if done correctly - should echo "value"
#     - run: echo ${{steps.output_test.outputs.new_value }}
