name: Add PR to project
on:
  pull_request:
    types:
      - ready_for_review
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          ORGANIZATION: ske-test-org
          PROJECT_NUMBER: 6
        run: |
          (gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectNext(number: $number) {
                  id, fields(first:20) {nodes {id, name, settings}}
                }
              }
            }' -F org=$ORGANIZATION -F number=$PROJECT_NUMBER
          ) > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectNext.id' project_data.json) >> $GITHUB_ENV
          echo 'DATE_FIELD_ID='$(jq '.data.organization.projectNext.fields.nodes[] | select(.name== "Date posted") | .id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectNext.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'TODO_OPTION_ID='$(jq '.data.organization.projectNext.fields.nodes[] | select(.name== "Status") |.settings | fromjson.options[] | select(.name=="Todo") |.id' project_data.json) >> $GITHUB_ENV

      - name: Add PR to project
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: |
          item_id="$( gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($proj:ID!, $pr:ID!) {
              addProjectNextItem(input: {projectId: $proj, contentId: $pr}) {
                projectNextItem {
                  id
                }
              }
            }' -F proj=${{ env.PROJECT_ID }} -F pr=$PR_ID --jq '.data.addProjectNextItem.projectNextItem.id')"
          
          echo 'ITEM_ID='$item_id >> $GITHUB_ENV
          
      - name: Set status
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($proj: ID!, $item: ID!, $field: ID!, $value: String!) {
              updateProjectNextItemField(input: {projectId: $proj, itemId: $item, fieldId: $field, value: $value}) {
                projectNextItem {
                  id
                }
              }
            }' -F proj=$PROJECT_ID -F item=$ITEM_ID -F field=${{ env.STATUS_FIELD_ID }} -F value=${{ env.TODO_OPTION_ID }}

      - name: Get date
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Set date
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            mutation($proj: ID!, $item: ID!, $field: ID!, $value: String!) {
              updateProjectNextItemField(input: {projectId: $proj, itemId: $item, fieldId: $field, value: $value}) {
                projectNextItem {
                  id
                }
              }
            }' -F proj=${{ env.PROJECT_ID }} -F item=${{ env.ITEM_ID }} -F field=${{ env.DATE_FIELD_ID }} -F value=${{ env.DATE }}
