name: Add PR to project
on:
  pull_request:
    types:
      - ready_for_review
jobs:
  add_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: print context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

#       - name: Label issues
#         uses: octokit/graphql-action@2.2.20
#         with:
#           query: |
#             query(){

#             }
#           pr_node_id: ${{ github.event.client_payload.command.resource.id }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
