name: CI
on:
  repository_dispatch:
    types: special_merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - name: Output command context
#         env:
#           COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
#         run: echo "$COMMAND_CONTEXT"
      - name: make gh call
        run: |
          gh auth login --with-token < ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          gh issue edit 1 --body "updated from wf"
