name: Transfer to Open Source Repo

# **What it does**: Copies internal issues to the open source repo
# **Why we have it**: To copy internal issues to the open source repo (since you can't transfer issues from our internal repo to the public repo)
# **Who does it impact**: Open source and docs-content maintainers

on:
  issues:
    types:
      - labeled

jobs:
  transfer-issue:
    name: Transfer issue
    runs-on: ubuntu-latest # TODO add conditional to check label
    steps:
      - name: version
        run: echo $(gh --version)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # todo change secret back to ${{secrets.DOCS_BOT_FR}}

      - name: Create an issue in the open source repo # todo change repo # todo use issue body/title
        run: echo 'NEW_ISSUE='$(gh issue create --title "${{ env.ISSUE_TITLE }}" --body "${{ env.ISSUE_BODY }}" --repo apm-pub-org/d3-1) >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # todo change secret back to ${{secrets.DOCS_BOT_FR}}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
      - name: Label new issue
        run: gh issue edit ${{ env.NEW_ISSUE }} --add-label "help wanted"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # todo change secret back to ${{secrets.DOCS_BOT_FR}}
      - name: Comment on old issue
        run: gh issue comment ${{ env.OLD_ISSUE }} --body "test"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # todo change secret back to ${{secrets.DOCS_BOT_FR}}
          OLD_ISSUE: ${{ github.event.issue.html_url }}
#           COMMENT: "This issue was transferred to the open source repo as ${{ env.NEW_ISSUE }}"
          COMMENT: "This issue was transferred to the open source repo as xxx"
      - name: Close old issue
        run: gh issue close ${{ github.event.issue.html_url }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # todo change secret back to ${{secrets.DOCS_BOT_FR}}
