name: Copy to Open Source Repo

# **What it does**: Copies internal issues to the open source repo
# **Why we have it**: To copy internal issues to the open source repo (since you can't transfer issues from our internal repo to the public repo)
# **Who does it impact**: Open source and docs-content maintainers

on:
  issues:
    types:
      - labeled

jobs:
  transfer-issue:
    name: Transfer issue
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ready for transfer to os'
    steps:
      - name: Create an issue in the open source repo
        run: echo 'NEW_ISSUE='$(gh issue create --title "${{ env.ISSUE_TITLE }}" --body "${{ env.ISSUE_BODY }}" --repo apm-pub-org/apm-pub-org-pub-repo) >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Label the new issue
        run: gh issue edit ${{ env.NEW_ISSUE }} --add-label "help wanted"
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Comment on the old issue
        run: gh issue comment ${{ github.event.issue.html_url }} --body "This issue was transferred to the open source repo as ${{ env.NEW_ISSUE }}"
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Close the old issue
        run: gh issue close ${{ github.event.issue.html_url }}
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

# TODO change PERSONAL_ACCESS_TOKEN to DOCS_BOT_FR
# TODO change repo to github/docs