name: CI
on:
  repository_dispatch:
    types: special_merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print context
        run: echo ${{ github.event }}
      - name: Remove issue from board
        if: ${{ github.event.client_payload.command.resource.type }} == 'Issue'
        run: gh issue edit "$PR_URL" --body "updated 6"
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          PR_URL: https://github.com/${{ github.event.client_payload.command.repository.full_name }}/issues/${{ github.event.client_payload.command.resource.number }}
#       - name: Remove PR from board
#         if: ${{ github.event.client_payload.command.resource.type == 'Issue'
#         run: gh issue edit "$PR_URL" --body "updated 6"
#         env:
#           GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
#           PR_URL: https://github.com/${{ github.event.client_payload.command.repository.full_name }}/issues/${{ github.event.client_payload.command.resource.number }}

# need to make sure works from diff repos, for issues and PRs
