name: Move assigned card
on:
  commit_comment
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: d3
          column: c3
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
