name: Remove card from FR board

on:
  repository_dispatch:
    types: remove_from_docs_FR_board

jobs:
  remove_from_FR_board:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      - run: echo yey
