name: Transfer to Open Source Repo

# **What it does**: Copies internal issues to the open source repo
# **Why we have it**: To copy internal issues to the open source repo (since you can't transfer issues from our internal repo to the public repo)
# **Who does it impact**: Open source and docs-content maintainers

on:
  issues:
    types:
      - labeled

jobs:
  transfer-issue:
    name: Transfer issue
    runs-on: ubuntu-latest # TODO add conditional to check label
    steps:
      - name: Create an issue in the open source repo
        run: gh issue create --title "test" --body "test" --repo apm-pub-org/d3-1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # todo change secret back to ${{secrets.DOCS_BOT_FR}}

      - name: Create an issue in the open source repo
        run: echo 'OUT='$(gh issue create --title "test2" --body "test2") >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # todo change secret back to ${{secrets.DOCS_BOT_FR}}
#           ISSUE_TITLE: ${{ github.event.issue.title }}
#           ISSUE_BODY: ${{ github.event.issue.body }}
      - name: echo test
        run: echo ${{ env.OUT }}
