name: CI
on:
  repository_dispatch:
    types: special_merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$COMMAND_CONTEXT"
#       - name: Enable auto-merge for new PRs
#         run: gh issue edit "$PR_URL" --body "updated from wf"
#         env:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
# #           PR_URL: ${{ github.event.client_payload.command.resource.id }}
#           PR_URL: https://github.com/apm-pub-org/d3-1/issues/1 
