name: CI
on:
  repository_dispatch:
    types: special_merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - name: Output command context
#         env:
#           COMMAND_CONTEXT: ${{ toJSON(github.event.client_payload) }}
#         run: echo "$COMMAND_CONTEXT"
      - name: Enable auto-merge for new PRs
        run: gh issue edit 1 --body "updated from wf"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
