name: Transfer to Open Source Repo

# **What it does**: Copies internal issues to the open source repo
# **Why we have it**: To copy internal issues to the open source repo (since you can't transfer issues from our internal repo to the public repo)
# **Who does it impact**: Open source and docs-content maintainers

on:
  issues:
    types:
      - labeled

jobs:
  transfer-issue:
    name: Transfer issue
    runs-on: ubuntu-latest # TODO add conditional to check label
    steps:
      # - name: Create an issue in the open source repo
      #   run: gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --repo github/docs
      #   env:
      #     GITHUB_TOKEN: ${{secrets.DOCS_BOT_FR}}
      #     ISSUE_TITLE: https://github.com/${{ github.event.client_payload.command.repository.full_name }}/pull/${{ github.event.client_payload.command.resource.number }}
      #     ISSUE_BODY: https://github.com/${{ github.event.client_payload.command.repository.full_name }}/pull/${{ github.event.client_payload.command.resource.number }}
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$COMMAND_CONTEXT"
