name: CI
on:
  repository_dispatch:
    types: special_merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output command context
        env:
          COMMAND_CONTEXT: ${{ toJSON(github.event) }}
          CAT: https://github.com/${{ github.event.client_payload.command.repository.full_name }}/issues/${{ github.event.client_payload.command.resource.number }}
        run: echo "$CAT"
      - name: Enable auto-merge for new PRs
        run: gh issue edit "$PR_URL" --body "updated 6"
#         run: gh issue edit https://github.com/apm-pub-org/d3-2/issues/1 --body "updated 5"
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          PR_URL: https://github.com/${{ github.event.client_payload.command.repository.full_name }}/issues/${{ github.event.client_payload.command.resource.number }}
#           PR_URL: https://github.com/apm-pub-org/d3-1/issues/1 
# TODO: need to get URL of triggering issue/PR instad of hardcoding, need to make sure works from diff repos, also add repo flag back in to command file
