name: Add review table

# **What it does**: 
# **Why we have it**: 
# **Who does it impact**: 

on:
  pull_request:
    types:
      - labeled

jobs:
  comment-that-approved:
    name: Add review template
    runs-on: ubuntu-latest
    if: github.event.label.name == 'review' # TODO sometimes also gate on repo
    steps:

      - name: Comment on the PR
        run: |
          gh pr comment $PR --body $COMMENT
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          PR: ${{ github.event.pull_request.html_url }}
          COMMENT: "line 1\nline2"
